### ISSUE TITLE
Links of BEGUN_BY and ENDED_BY depend on the property AdjacentVerbTimex.numInterWords

### ISSUE THREAD

**Issue by assaft** [assaft/caevo#8]
Running the sentence _John taught from 1994 through 1999_ (from test t14) with the property **AdjacentVerbTimex.numInterWords=8** returns the expected result:
ei1,taught
t1,1994
t2,1999
l1,ei1,t1,**BEGUN_BY**
l2,ei1,t2,**ENDED_BY**

However, running it without the property returns:
ei1,taught
t1,1994
t2,1999
l1,ei1,t1,**IS_INCLUDED**
l2,ei1,t2,**IS_INCLUDED**

Is this the expected behavior?

**Comment by ymishory** [comment]
Without the property, the AdjacentVerbTimex sieve uses a default value of 0. This effectively makes the sieve useless, and could definitely cause such results.
